on:
  workflow_dispatch:
    inputs:
      check_config:
        type: boolean
        description: 'Fail when configuration overridden'
        required: true
        default: true
      sql_backup:
        type: boolean
        description: 'Create SQL backup'
        required: true
        default: true
      enable_maintenance_mode:
        type: boolean
        description: 'Enable maintenance mode.'
        required: true
        default: true

name: 'Deploy PROD instance'
jobs:
  create_release_archive:
    uses: ./.github/workflows/lib.create-release-archive.yml
    with:
      php_version:           ${{ vars.PROD_PHP_VERSION }}
      checkout_ref:          ${{ github.event.release.tag_name }}
      enable_nodejs:         ${{ vars.ENABLE_NODEJS }}
      node_version_file:     ${{ vars.NODE_VERSION_FILE }}
      compile_theme_script:  ${{ vars.COMPILE_THEME_SCRIPT }}
      use_ref_as_release_id: true

  deploy_release_app2:
    uses: ./.github/workflows/lib.deploy-release.yml
    needs: create_release_archive
    with:
      release_id:              ${{ needs.create_release_archive.outputs.release_id }}
      release_filename:        ${{ needs.create_release_archive.outputs.release_filename }}
      project_dir:             ${{ vars.PROD_PROJECT_DIR }}
      artifacts_dir:           ${{ vars.PROD_ARTIFACTS_DIR }}
      settings_file:           ${{ vars.PROD_SETTINGS_FILE }}
      public_files_dir:        ${{ vars.PROD_PUBLIC_FILES_DIR }}
      robo_file:               ${{ vars.PROD_ROBO_FILE }}
      check_config:            ${{ inputs.check_config }}
      sql_backup:              ${{ inputs.sql_backup }}
      delete_release_filename: false
    secrets:
      ssh_user: ${{ secrets.PROD_SSH_USER }}
      ssh_host: ${{ secrets.PROD_SSH_HOST_APP2 }}
      ssh_key:  ${{ secrets.PROD_SSH_KEY }}

  deploy_release_app1:
    uses: ./.github/workflows/lib.deploy-release.yml
    needs: [create_release_archive, deploy_release_app2]
    with:
      release_id:          ${{ needs.create_release_archive.outputs.release_id }}
      release_filename:    ${{ needs.create_release_archive.outputs.release_filename }}
      project_dir:         ${{ vars.PROD_PROJECT_DIR }}
      artifacts_dir:       ${{ vars.PROD_ARTIFACTS_DIR }}
      settings_file:       ${{ vars.PROD_SETTINGS_FILE }}
      public_files_dir:    ${{ vars.PROD_PUBLIC_FILES_DIR }}
      robo_file:           ${{ vars.PROD_ROBO_FILE }}
      check_config:        ${{ inputs.check_config }}
      sql_backup:          ${{ inputs.sql_backup }}
    secrets:
      ssh_user: ${{ secrets.PROD_SSH_USER }}
      ssh_host: ${{ secrets.PROD_SSH_HOST }}
      ssh_key:  ${{ secrets.PROD_SSH_KEY }}

  update_instance:
    uses: ./.github/workflows/lib.update-instance.yml
    needs: deploy_release_app1
    with:
      project_dir:             ${{ vars.PROD_PROJECT_DIR }}
      enable_maintenance_mode: ${{ inputs.enable_maintenance_mode }}
      cleanup_dir:             ${{ vars.PROD_ARTIFACTS_DIR }}
      retain:                  ${{ vars.RETAIN_RELEASES }}
      deployment_url:          ${{ vars.PROD_URL }}
      notify_success:          true
      multisite:              true
    secrets:
      ssh_user:           ${{ secrets.PROD_SSH_USER }}
      ssh_host:           ${{ secrets.PROD_SSH_HOST }}
      ssh_host_app2:      ${{ secrets.PROD_SSH_HOST_APP2 }}
      ssh_key:            ${{ secrets.PROD_SSH_KEY }}
      statuscake_api_key: ${{ secrets.STATUSCAKE_API_KEY }}
      statuscake_test_id: ${{ secrets.PROD_STATUSCAKE_ID }}
      discord_webhook:    ${{ secrets.DISCORD_WEBHOOK }}

  notify_failure:
    uses: ./.github/workflows/lib.notify-failure.yml
    needs: [create_release_archive, deploy_release_app2, deploy_release_app1, update_instance]
    if: failure()
    with:
      deployment_url: ${{ vars.PROD_URL }}
    secrets:
      discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
