# .github/workflows/lib.deploy-release-multisite.yml
on:
  workflow_call:
    inputs:
      runner:
        type: string
        required: false
        default: 'drupal-runner-v2'
      release_id:
        type: string
        required: true
      release_filename:
        type: string
        required: true
      project_dir:
        type: string
        required: true
      artifacts_dir:
        type: string
        required: true
      settings_file:
        type: string
        required: true
      public_files_dir:
        type: string
        required: true
      robo_file:
        type: string
        required: true
      local_services_file:
        type: string
        required: false
        default: ''
      database_dump_dir:
        type: string
        required: false
        default: ''
      check_config:
        type: boolean
        required: false
        default: false
      sql_backup:
        type: boolean
        required: false
        default: true
      artifacts_lifespan:
        type: number
        required: false
        default: 30
    secrets:
      ssh_user:
        required: true
      ssh_host_app1:
        required: true
      ssh_host_app2:
        required: true
      ssh_key:
        required: true

jobs:
  deploy_release:
    name: 'Deploy release on the server'
    runs-on: ${{ inputs.runner }}
    steps:
      - name: 'Deploy release on the server app2'
        uses: eaudeweb/drupal-deploy-action@30342-multiple-instances-drupal
        with:
          ssh_user:            ${{ secrets.ssh_user }}
          ssh_host:            ${{ secrets.ssh_host_app2 }}
          ssh_key:             ${{ secrets.ssh_key }}
          release_id:          ${{ inputs.release_id }}
          release_filename:    ${{ inputs.release_filename }}
          project_dir:         ${{ inputs.project_dir }}
          artifacts_dir:       ${{ inputs.artifacts_dir }}
          settings_file:       ${{ inputs.settings_file }}
          public_files_dir:    ${{ inputs.public_files_dir }}
          robo_file:           ${{ inputs.robo_file }}
          local_services_file: ${{ inputs.local_services_file }}
          check_config:        ${{ inputs.check_config }}
          sql_backup:          ${{ inputs.sql_backup }}
          artifacts_lifespan:  ${{ inputs.artifacts_lifespan }}

      - name: 'Deploy release on the server app1'
        uses: eaudeweb/drupal-deploy-action@2.x
        with:
          ssh_user:            ${{ secrets.ssh_user }}
          ssh_host:            ${{ secrets.ssh_host_app1 }}
          ssh_key:             ${{ secrets.ssh_key }}
          release_id:          ${{ inputs.release_id }}
          release_filename:    ${{ inputs.release_filename }}
          project_dir:         ${{ inputs.project_dir }}
          artifacts_dir:       ${{ inputs.artifacts_dir }}
          settings_file:       ${{ inputs.settings_file }}
          public_files_dir:    ${{ inputs.public_files_dir }}
          robo_file:           ${{ inputs.robo_file }}
          local_services_file: ${{ inputs.local_services_file }}
          check_config:        ${{ inputs.check_config }}
          sql_backup:          ${{ inputs.sql_backup }}
          artifacts_lifespan:  ${{ inputs.artifacts_lifespan }}
